ALLOWED_AUDIT_TABLES = {
    "filaments",
    "filament_mounting",
    "filament_acclimatization",
    "lids",
    "seals",
    "product_requests",
    "product_harvest",
    "product_quality_control",
    "product_tracking",
    "treatment_batches",
    "treatment_batch_products",
    "post_treatment_inspections",
    "users",
    "orders",
    "order_items",
    "order_supplements",
    "supplements"
}