-- INSERT INTO dbo.filaments
--     (serial_number, lot_number, location_id, weight_grams, received_by, qc_result)
-- SELECT
--     v.serial_number, v.lot_number, s.id, v.weight_grams, u.id, v.qc_result
-- FROM (VALUES
--     ('123ABC-1', '123ABC', '2250', 8000, 'steve@yourcompany.com', 'PASS'),
--     ('123ABC-2', '123ABC', '2250', 8000, 'arthur@yourcompany.com', 'PASS'),
--     ('123ABC-3', '123ABC', '2250', 8000, 'arthur@yourcompany.com', 'PASS'),
--     ('456DEF-1', '456DEF', '2250', 8000, 'arthur@yourcompany.com', 'FAIL'),
--     ('456DEF-2', '456DEF', '2250', 8000, 'arthur@yourcompany.com', 'FAIL'),
--     ('456DEF-3', '456DEF', '2250', 8000, 'arthur@yourcompany.com', 'FAIL')
-- ) AS v(serial_number, lot_number, location_name, weight_grams, received_upn, qc_result)
-- JOIN dbo.storage_locations s 
--     ON s.location_name = v.location_name
-- JOIN dbo.users u 
--     ON u.user_principal_name = v.received_upn
-- LEFT JOIN dbo.filaments f 
--     ON f.serial_number = v.serial_number
-- WHERE f.id IS NULL;
