-- INSERT INTO dbo.filament_acclimatization (filament_id, moved_by, moved_at, status)
-- SELECT f.id, u.id, DATEADD(DAY, v.offset_days, GETDATE()), v.status
-- FROM (VALUES
--     ('123ABC-1', 0, 'Acclimatizing'),
--     ('123ABC-2', -5, 'Acclimatizing'),
--     ('123ABC-3', 3, 'Acclimatizing')
-- ) AS v(serial_number, offset_days, status)
-- JOIN dbo.filaments f 
--     ON f.serial_number = v.serial_number
-- JOIN dbo.users u 
--     ON u.user_principal_name = 'steve@yourcompany.com'
-- LEFT JOIN dbo.filament_acclimatization fa 
--     ON fa.filament_id = f.id 
-- WHERE fa.id IS NULL;